# Generated by Django 5.0.7 on 2024-10-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
