# Generated by Django 5.0.7 on 2024-10-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_api', '0002_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
