# Generated by Django 5.0.7 on 2024-10-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_api', '0003_remove_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='category',
            field=models.CharField(choices=[('aftermarket', 'Aftermarket'), ('export', 'Export'), ('return', 'Return')], default='aftermarket', max_length=20),
        ),
    ]
