# Generated by Django 5.0.7 on 2024-10-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_api', '0004_sale_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='category',
            field=models.CharField(choices=[('aftermarket', 'Aftermarket'), ('export', 'Export')], default='aftermarket', max_length=20),
        ),
    ]
