# Generated by Django 5.0.7 on 2024-10-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_api', '0005_alter_sale_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='region_type',
            field=models.CharField(choices=[('local', 'Local'), ('international', 'International')], default='local', max_length=20),
        ),
    ]
